# Generated by Django 3.2.16 on 2022-12-05 14:18

from django.db import migrations

def generate_data(apps, schema_editor):
    Author = apps.get_model("app1", "Author")
    Book = apps.get_model("app1", "Book")
    a = Author.objects.create(name="some name")
    b = Book.objects.create(author=a)


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(code=generate_data, reverse_code=lambda *args, **kwargs: "No reverse needed")
    ]
